address: https://test-stand.gb.ru
sleep_time: 1
browser: firefox
wait: 5
login: KiraZ2
passwd: gi89mjb90f
title: THE NEW POST CREATED BY SELENIUM
description: OMG! SELENIUM HERE!
content: THIS IS CONTENT POSTET BY SELENIUM!
